name: Build

on:
  pull_request:
    branches: [ "main", "develop" ]
  workflow_call:
    inputs:
      version:
        description: 'The version of the release (e.g. 1.0.0)'
        required: false
        type: string
        default: develop
      upload_artifacts:
        description: 'Upload the artifacts'
        required: false
        type: boolean
        default: false
      overwrite_sha:
        description: 'Overwrite the SHA of the commit to build'
        required: false
        type: string

run-name: Build+${{ github.run_number }} build/${{ github.sha }}

jobs:
  build:

    name: 🔨 Build GermanRP Addon
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
        ref: ${{ inputs.overwrite_sha || github.sha }}

    - name: Set up JDK
      uses: actions/setup-java@v5
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        VERSION: ${{ inputs.version }}
      run: ./gradlew build --full-stacktrace

    - if: inputs.upload_artifacts == true
      name: Upload Artifact
      uses: actions/upload-artifact@v5
      with:
        name: Artifacts
        path: build/libs/*-release.jar
