name: Build

on:
  pull_request:
    branches: [ "main", "develop" ]
  schedule:
    - cron: "55 1 * * *" # 5 Minutes before Server restart
  workflow_dispatch:


run-name: Build+${{ github.run_number }} build/${{ github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  build:

    name: 🔨 Build GermanRP Addon
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Set Build Version
      if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
      run: |
        VERSION=nightly-$(git rev-parse --short HEAD)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Build with Gradle
      env:
        VERSION: $ {{ env.VERSION }}
      run: ./gradlew build --full-stacktrace

    - name: Upload Build Artifact
      uses: actions/upload-artifact@4.6.2
      with:
        name: germanrp-addon-release
        path: build/libs/germanrp-addon-release.jar

  release:

    if: ${{ github.event_name == 'schedule' || github.event_name == 'workflow_dispatch' }}
    name: 🚀 Nightly Release
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download Build Artifact
        uses: actions/download-artifact@4.3.0
        with:
          name: germanrp-addon-release
          path: ./artifacts

      - name: Create a Nightly Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          TAG_NAME="nightly"
          RELEASE_NAME="Nightly Build - $(date -u +"%Y-%m-%d %H:%M:%S")"
          gh release create "$TAG_NAME" \
            --title "$RELEASE_NAME" \
            --notes "Hinweis: Dies ist ein Nightly-Build. Dieser Build wird automatisch generiert und kann Fehler enthalten oder nicht ordnungsgemäß funktionieren." \
            --prerelease \
            --target develop \
            ./artifacts/germanrp-addon-release.jar
