name: create-release-notes.yml

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      nightly:
        required: true
        type: boolean

jobs:
  create-release-notes:

    name: 📑 Create release notes
    runs-on: ubuntu-latest

    steps:
    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: Artifacts
        path: artifacts/

    - if: inputs.nightly == 'true'
      name: Create release notes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: 'nightly'
      run: |
        RELEASE_NOTES="Dies ist ein automatisch erstellter Nightly-Build. Er kann neue Features oder Änderungen enthalten, die noch nicht fertiggestellt sind. Dieser Build ist nur für Tests gedacht. Es kann passieren, dass er Fehler hat oder nicht richtig funktioniert."
        gh release create "$tag" \
          --title "$tag" \
          --notes "$RELEASE_NOTES" \
          --prerelease \
          --target develop \
          artifacts/*-release.jar

    - if: inputs.nightly == 'false'
      name: Create release notes nightly
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        tag: ${{ inputs.version }}
      run: |
        gh release create "$tag" \
          --title "$tag" \
          --target main \
          --generate-notes \
          artifacts/*-release.jar
