name: Build Addon for LabyMod Store

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: VERSION=$(git tag --sort=-creatordate | grep -v "nightly" | head -n 1) ./gradlew build --full-stacktrace

      - name: Upload Artifact
        uses: actions/upload-artifact@v4

        with:
          name: Artifacts
          path: build/libs/*-release.jar
