name: Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      version:
        description: 'The version of the release (e.g. 1.0.0)'
        required: true
        type: string

run-name: Build+${{ github.run_number }} release/${{ github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:

    name: 🎉 Release GermanRP Addon
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      env:
        VERSION: ${{ inputs.version }}
      run: ./gradlew build --full-stacktrace

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: build/libs/*-release.jar

    - name: Trigger release notes creation
      uses: ./.github/workflows/create-release-notes.yml
      with:
        nightly: false
        version: ${{ inputs.version }}
