name: Release

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

run-name: Build+${{ github.run_number }} release/${{ github.sha }}

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  release:

    name: 🎉 Release GermanRP Addon
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: main
        fetch-depth: 0

    - name: Set up JDK
      uses: actions/setup-java@v4
      with:
        java-version: '23'
        distribution: 'temurin'
        cache: gradle

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4

    - name: Build with Gradle
      run: ./gradlew build --full-stacktrace

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: Artifacts
        path: build/libs/*-release.jar
